version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - DB_USER=admin
      - DB_PWD=adminpass
      - DB_SERVER=mysql
      - DB_NAME=team-member-projects
    volumes:
    - mysql-data:/var/lib/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8085:80
    environment:
      - PMA_HOST=mysql
    container_name: phpmyadmin
volumes:
  mysql-data:
    driver: local